CREATE TABLE rangos_militares (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_eliminacion TIMESTAMP,
    fuerza VARCHAR(40) NOT NULL,
    nombre VARCHAR(120) NOT NULL,
    orden_jerarquico INTEGER NOT NULL,
    CONSTRAINT uk_rango_militar_fuerza_nombre UNIQUE (fuerza, nombre)
);

CREATE TABLE unidades_militares (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_eliminacion TIMESTAMP,
    fuerza VARCHAR(40) NOT NULL,
    nombre VARCHAR(180) NOT NULL,
    sigla VARCHAR(40),
    tipo_unidad VARCHAR(80),
    descripcion TEXT,
    CONSTRAINT uk_unidad_militar_fuerza_nombre UNIQUE (fuerza, nombre)
);

ALTER TABLE actuaciones_veteranos ADD COLUMN rango_id BIGINT;
ALTER TABLE actuaciones_veteranos ADD COLUMN unidad_id BIGINT;

ALTER TABLE actuaciones_veteranos
    ADD CONSTRAINT fk_actuaciones_veteranos_rango FOREIGN KEY (rango_id) REFERENCES rangos_militares (id);

ALTER TABLE actuaciones_veteranos
    ADD CONSTRAINT fk_actuaciones_veteranos_unidad FOREIGN KEY (unidad_id) REFERENCES unidades_militares (id);

CREATE INDEX idx_rango_militar_fuerza_activo ON rangos_militares (fuerza, activo);
CREATE INDEX idx_rango_militar_orden ON rangos_militares (fuerza, orden_jerarquico);
CREATE INDEX idx_unidad_militar_fuerza_activo ON unidades_militares (fuerza, activo);
CREATE INDEX idx_unidad_militar_nombre ON unidades_militares (nombre);
CREATE INDEX idx_unidad_militar_sigla ON unidades_militares (sigla);
CREATE INDEX idx_actuacion_veterano_rango ON actuaciones_veteranos (rango_id);
CREATE INDEX idx_actuacion_veterano_unidad ON actuaciones_veteranos (unidad_id);

INSERT INTO rangos_militares (fuerza, nombre, orden_jerarquico) VALUES
    ('EJERCITO', 'Soldado conscripto', 10),
    ('EJERCITO', 'Cabo', 20),
    ('EJERCITO', 'Cabo Primero', 30),
    ('EJERCITO', 'Sargento', 40),
    ('EJERCITO', 'Sargento Primero', 50),
    ('EJERCITO', 'Subteniente', 60),
    ('EJERCITO', 'Teniente', 70),
    ('EJERCITO', 'Teniente Primero', 80),
    ('EJERCITO', 'Capitan', 90),
    ('EJERCITO', 'Mayor', 100),
    ('EJERCITO', 'Teniente Coronel', 110),
    ('EJERCITO', 'Coronel', 120),
    ('ARMADA', 'Marinero conscripto', 10),
    ('ARMADA', 'Cabo Segundo', 20),
    ('ARMADA', 'Cabo Primero', 30),
    ('ARMADA', 'Suboficial Segundo', 40),
    ('ARMADA', 'Guardiamarina', 50),
    ('ARMADA', 'Teniente de Corbeta', 60),
    ('ARMADA', 'Teniente de Fragata', 70),
    ('ARMADA', 'Teniente de Navio', 80),
    ('ARMADA', 'Capitan de Corbeta', 90),
    ('ARMADA', 'Capitan de Fragata', 100),
    ('ARMADA', 'Capitan de Navio', 110),
    ('FUERZA_AEREA', 'Soldado conscripto', 10),
    ('FUERZA_AEREA', 'Cabo', 20),
    ('FUERZA_AEREA', 'Cabo Primero', 30),
    ('FUERZA_AEREA', 'Suboficial Auxiliar', 40),
    ('FUERZA_AEREA', 'Alferez', 50),
    ('FUERZA_AEREA', 'Teniente', 60),
    ('FUERZA_AEREA', 'Primer Teniente', 70),
    ('FUERZA_AEREA', 'Capitan', 80),
    ('FUERZA_AEREA', 'Mayor', 90),
    ('FUERZA_AEREA', 'Vicecomodoro', 100),
    ('FUERZA_AEREA', 'Comodoro', 110),
    ('PREFECTURA', 'Marinero', 10),
    ('PREFECTURA', 'Cabo Segundo', 20),
    ('PREFECTURA', 'Cabo Primero', 30),
    ('PREFECTURA', 'Ayudante de Tercera', 40),
    ('PREFECTURA', 'Oficial Ayudante', 50),
    ('PREFECTURA', 'Oficial Principal', 60),
    ('PREFECTURA', 'Prefecto', 70),
    ('GENDARMERIA', 'Gendarme', 10),
    ('GENDARMERIA', 'Cabo', 20),
    ('GENDARMERIA', 'Cabo Primero', 30),
    ('GENDARMERIA', 'Sargento', 40),
    ('GENDARMERIA', 'Subalferez', 50),
    ('GENDARMERIA', 'Alferez', 60),
    ('GENDARMERIA', 'Primer Alferez', 70),
    ('GENDARMERIA', 'Comandante Principal', 80),
    ('CIVIL', 'Civil', 10);

INSERT INTO unidades_militares (fuerza, nombre, sigla, tipo_unidad, descripcion) VALUES
    ('EJERCITO', 'Regimiento de Infanteria 25', 'RI 25', 'Regimiento', 'Unidad del Ejercito Argentino desplegada en operaciones en Malvinas.'),
    ('EJERCITO', 'Regimiento de Infanteria Mecanizado 3 General Belgrano', 'RI Mec 3', 'Regimiento', 'Unidad del Ejercito Argentino participante del conflicto.'),
    ('EJERCITO', 'Regimiento de Infanteria Mecanizado 6 General Viamonte', 'RI Mec 6', 'Regimiento', 'Unidad del Ejercito Argentino desplegada durante el conflicto.'),
    ('EJERCITO', 'Regimiento de Infanteria 7 Coronel Conde', 'RI 7', 'Regimiento', 'Unidad del Ejercito Argentino desplegada en la defensa terrestre.'),
    ('EJERCITO', 'Regimiento de Infanteria 12 General Arenales', 'RI 12', 'Regimiento', 'Unidad del Ejercito Argentino participante de operaciones terrestres.'),
    ('EJERCITO', 'Compania de Comandos 601', 'Ca Cdos 601', 'Compania', 'Unidad de comandos del Ejercito Argentino.'),
    ('EJERCITO', 'Grupo de Artilleria Aerotransportado 4', 'GAA 4', 'Grupo de artilleria', 'Unidad de artilleria del Ejercito Argentino.'),
    ('ARMADA', 'Batallon de Infanteria de Marina 5', 'BIM 5', 'Batallon', 'Unidad de Infanteria de Marina desplegada en Malvinas.'),
    ('ARMADA', 'Batallon de Infanteria de Marina 2', 'BIM 2', 'Batallon', 'Unidad de Infanteria de Marina vinculada al conflicto.'),
    ('ARMADA', 'Agrupacion de Comandos Anfibios', 'APCA', 'Agrupacion', 'Unidad de comandos anfibios de la Armada Argentina.'),
    ('ARMADA', 'Crucero ARA General Belgrano', 'ARA General Belgrano', 'Buque', 'Unidad naval argentina hundida durante el conflicto.'),
    ('ARMADA', 'Aviso ARA Alferez Sobral', 'ARA Alferez Sobral', 'Buque', 'Aviso de la Armada Argentina participante del conflicto.'),
    ('FUERZA_AEREA', 'Grupo 5 de Caza', 'G5C', 'Grupo aereo', 'Unidad de la Fuerza Aerea Argentina con despliegue operativo en el conflicto.'),
    ('FUERZA_AEREA', 'Grupo 4 de Caza', 'G4C', 'Grupo aereo', 'Unidad de la Fuerza Aerea Argentina participante del conflicto.'),
    ('FUERZA_AEREA', 'Grupo 6 de Caza', 'G6C', 'Grupo aereo', 'Unidad de la Fuerza Aerea Argentina participante del conflicto.'),
    ('FUERZA_AEREA', 'Base Aerea Militar Condor', 'BAM Condor', 'Base aerea', 'Base aerea militar argentina en Malvinas.'),
    ('FUERZA_AEREA', 'Base Aerea Militar Malvinas', 'BAM Malvinas', 'Base aerea', 'Base aerea militar argentina en Malvinas.'),
    ('PREFECTURA', 'Guardacostas GC-82 Islas Malvinas', 'GC-82', 'Guardacostas', 'Guardacostas de Prefectura Naval Argentina vinculado al conflicto.'),
    ('PREFECTURA', 'Guardacostas GC-83 Rio Iguazu', 'GC-83', 'Guardacostas', 'Guardacostas de Prefectura Naval Argentina atacado durante el conflicto.'),
    ('GENDARMERIA', 'Escuadron Alacran', 'Esc Alacran', 'Escuadron', 'Unidad especial de Gendarmeria Nacional desplegada durante el conflicto.');
