UPDATE rangos_militares
SET activo = false, eliminado = true, fecha_eliminacion = CURRENT_TIMESTAMP
WHERE fuerza IN ('EJERCITO', 'FUERZA_AEREA', 'ARMADA', 'PREFECTURA', 'GENDARMERIA', 'CIVIL');

INSERT INTO rangos_militares (fuerza, nombre, orden_jerarquico, activo, eliminado, fecha_eliminacion) VALUES
    ('EJERCITO', 'Teniente General', 10, true, false, null),
    ('EJERCITO', 'General de División', 20, true, false, null),
    ('EJERCITO', 'General de Brigada', 30, true, false, null),
    ('EJERCITO', 'Coronel Mayor', 40, true, false, null),
    ('EJERCITO', 'Coronel', 50, true, false, null),
    ('EJERCITO', 'Teniente Coronel', 60, true, false, null),
    ('EJERCITO', 'Mayor', 70, true, false, null),
    ('EJERCITO', 'Capitán', 80, true, false, null),
    ('EJERCITO', 'Teniente Primero', 90, true, false, null),
    ('EJERCITO', 'Teniente', 100, true, false, null),
    ('EJERCITO', 'Subteniente', 110, true, false, null),
    ('EJERCITO', 'Suboficial Mayor', 120, true, false, null),
    ('EJERCITO', 'Suboficial Principal', 130, true, false, null),
    ('EJERCITO', 'Sargento Ayudante', 140, true, false, null),
    ('EJERCITO', 'Sargento Primero', 150, true, false, null),
    ('EJERCITO', 'Sargento', 160, true, false, null),
    ('EJERCITO', 'Cabo Primero', 170, true, false, null),
    ('EJERCITO', 'Cabo', 180, true, false, null),
    ('FUERZA_AEREA', 'Brigadier General', 10, true, false, null),
    ('FUERZA_AEREA', 'Brigadier Mayor', 20, true, false, null),
    ('FUERZA_AEREA', 'Brigadier', 30, true, false, null),
    ('FUERZA_AEREA', 'Comodoro Mayor', 40, true, false, null),
    ('FUERZA_AEREA', 'Comodoro', 50, true, false, null),
    ('FUERZA_AEREA', 'Vicecomodoro', 60, true, false, null),
    ('FUERZA_AEREA', 'Mayor', 70, true, false, null),
    ('FUERZA_AEREA', 'Capitán', 80, true, false, null),
    ('FUERZA_AEREA', 'Primer Teniente', 90, true, false, null),
    ('FUERZA_AEREA', 'Teniente', 100, true, false, null),
    ('FUERZA_AEREA', 'Alférez', 110, true, false, null),
    ('FUERZA_AEREA', 'Suboficial Mayor', 120, true, false, null),
    ('FUERZA_AEREA', 'Suboficial Principal', 130, true, false, null),
    ('FUERZA_AEREA', 'Suboficial Ayudante', 140, true, false, null),
    ('FUERZA_AEREA', 'Suboficial Auxiliar', 150, true, false, null),
    ('FUERZA_AEREA', 'Cabo Principal', 160, true, false, null),
    ('FUERZA_AEREA', 'Cabo Primero', 170, true, false, null),
    ('FUERZA_AEREA', 'Cabo', 180, true, false, null),
    ('ARMADA', 'Almirante', 10, true, false, null),
    ('ARMADA', 'Vicealmirante', 20, true, false, null),
    ('ARMADA', 'Contraalmirante', 30, true, false, null),
    ('ARMADA', 'Comodoro de Marina', 40, true, false, null),
    ('ARMADA', 'Capitán de Navío', 50, true, false, null),
    ('ARMADA', 'Capitán de Fragata', 60, true, false, null),
    ('ARMADA', 'Capitán de Corbeta', 70, true, false, null),
    ('ARMADA', 'Teniente de Navío', 80, true, false, null),
    ('ARMADA', 'Teniente de Fragata', 90, true, false, null),
    ('ARMADA', 'Teniente de Corbeta', 100, true, false, null),
    ('ARMADA', 'Guardiamarina', 110, true, false, null),
    ('ARMADA', 'Suboficial Mayor', 120, true, false, null),
    ('ARMADA', 'Suboficial Principal', 130, true, false, null),
    ('ARMADA', 'Suboficial Primero', 140, true, false, null),
    ('ARMADA', 'Suboficial Segundo', 150, true, false, null),
    ('ARMADA', 'Cabo Principal', 160, true, false, null),
    ('ARMADA', 'Cabo Primero', 170, true, false, null),
    ('ARMADA', 'Cabo Segundo', 180, true, false, null),
    ('PREFECTURA', 'Prefecto General (Prefecto Nacional Naval / Subprefecto Nacional Naval)', 10, true, false, null),
    ('PREFECTURA', 'Prefecto General', 20, true, false, null),
    ('PREFECTURA', 'Prefecto Mayor', 30, true, false, null),
    ('PREFECTURA', 'Prefecto Principal', 40, true, false, null),
    ('PREFECTURA', 'Prefecto', 50, true, false, null),
    ('PREFECTURA', 'Subprefecto', 60, true, false, null),
    ('PREFECTURA', 'Oficial Principal', 70, true, false, null),
    ('PREFECTURA', 'Oficial Auxiliar', 80, true, false, null),
    ('PREFECTURA', 'Oficial Ayudante', 90, true, false, null),
    ('PREFECTURA', 'Subprefecto Auxiliar', 100, true, false, null),
    ('PREFECTURA', 'Ayudante Mayor', 110, true, false, null),
    ('PREFECTURA', 'Ayudante Principal', 120, true, false, null),
    ('PREFECTURA', 'Ayudante de Primera', 130, true, false, null),
    ('PREFECTURA', 'Ayudante de Segunda', 140, true, false, null),
    ('PREFECTURA', 'Ayudante de Tercera', 150, true, false, null),
    ('PREFECTURA', 'Cabo Primero', 160, true, false, null),
    ('PREFECTURA', 'Cabo Segundo', 170, true, false, null),
    ('GENDARMERIA', 'Comandante General', 10, true, false, null),
    ('GENDARMERIA', 'Comandante Mayor', 20, true, false, null),
    ('GENDARMERIA', 'Comandante Principal', 30, true, false, null),
    ('GENDARMERIA', 'Comandante', 40, true, false, null),
    ('GENDARMERIA', 'Segundo Comandante', 50, true, false, null),
    ('GENDARMERIA', 'Primer Alférez', 60, true, false, null),
    ('GENDARMERIA', 'Alférez', 70, true, false, null),
    ('GENDARMERIA', 'Suboficial Mayor', 80, true, false, null),
    ('GENDARMERIA', 'Suboficial Principal', 90, true, false, null),
    ('GENDARMERIA', 'Sargento Ayudante', 100, true, false, null),
    ('GENDARMERIA', 'Sargento Primero', 110, true, false, null),
    ('GENDARMERIA', 'Sargento', 120, true, false, null),
    ('GENDARMERIA', 'Cabo Primero', 130, true, false, null),
    ('GENDARMERIA', 'Cabo', 140, true, false, null)
ON CONFLICT (fuerza, nombre) DO UPDATE SET
    orden_jerarquico = EXCLUDED.orden_jerarquico,
    activo = true,
    eliminado = false,
    fecha_eliminacion = null;
