CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_eliminacion TIMESTAMP,
    keycloak_id VARCHAR(100) NOT NULL,
    nombre VARCHAR(120) NOT NULL,
    email VARCHAR(160) NOT NULL,
    fecha_creacion TIMESTAMP NOT NULL,
    CONSTRAINT uk_usuarios_keycloak_id UNIQUE (keycloak_id),
    CONSTRAINT uk_usuarios_email UNIQUE (email)
);

CREATE TABLE objetos_museo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_eliminacion TIMESTAMP,
    numero_inventario VARCHAR(80) NOT NULL,
    nombre VARCHAR(160) NOT NULL,
    tipo_objeto VARCHAR(100),
    descripcion TEXT,
    CONSTRAINT uk_objetos_museo_numero_inventario UNIQUE (numero_inventario)
);

CREATE TABLE objetos_digitales (
    id BIGINT PRIMARY KEY,
    formato_digital VARCHAR(80),
    identificador_digital VARCHAR(120),
    metadatos TEXT,
    CONSTRAINT fk_objetos_digitales_objeto FOREIGN KEY (id) REFERENCES objetos_museo (id)
);

CREATE TABLE categoria_objeto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_eliminacion TIMESTAMP,
    nombre VARCHAR(100) NOT NULL,
    descripcion VARCHAR(500),
    CONSTRAINT uk_categoria_objeto_nombre UNIQUE (nombre)
);

CREATE TABLE objeto_categoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_eliminacion TIMESTAMP,
    objeto_museo_id BIGINT NOT NULL,
    categoria_objeto_id BIGINT NOT NULL,
    observaciones TEXT,
    CONSTRAINT uk_objeto_categoria UNIQUE (objeto_museo_id, categoria_objeto_id),
    CONSTRAINT fk_objeto_categoria_objeto FOREIGN KEY (objeto_museo_id) REFERENCES objetos_museo (id),
    CONSTRAINT fk_objeto_categoria_categoria FOREIGN KEY (categoria_objeto_id) REFERENCES categoria_objeto (id)
);

CREATE TABLE depositantes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_eliminacion TIMESTAMP,
    nombre VARCHAR(160) NOT NULL,
    tipo VARCHAR(30) NOT NULL,
    contacto VARCHAR(160),
    observaciones TEXT
);

CREATE TABLE objeto_depositante (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_eliminacion TIMESTAMP,
    objeto_museo_id BIGINT NOT NULL,
    depositante_id BIGINT NOT NULL,
    fecha_deposito DATE,
    tipo_deposito VARCHAR(80),
    observaciones TEXT,
    CONSTRAINT uk_objeto_depositante UNIQUE (objeto_museo_id, depositante_id),
    CONSTRAINT fk_objeto_depositante_objeto FOREIGN KEY (objeto_museo_id) REFERENCES objetos_museo (id),
    CONSTRAINT fk_objeto_depositante_depositante FOREIGN KEY (depositante_id) REFERENCES depositantes (id)
);

CREATE TABLE veteranos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_eliminacion TIMESTAMP,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    fuerza VARCHAR(40) NOT NULL,
    fecha_nacimiento DATE,
    fecha_fallecimiento DATE,
    historia TEXT
);

CREATE TABLE actuaciones_veteranos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_eliminacion TIMESTAMP,
    veterano_id BIGINT NOT NULL,
    rango VARCHAR(80),
    unidad VARCHAR(120),
    rol VARCHAR(120),
    fecha_inicio DATE,
    fecha_fin DATE,
    descripcion TEXT,
    CONSTRAINT fk_actuaciones_veteranos_veterano FOREIGN KEY (veterano_id) REFERENCES veteranos (id)
);

CREATE TABLE objeto_veterano (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_eliminacion TIMESTAMP,
    objeto_museo_id BIGINT NOT NULL,
    veterano_id BIGINT NOT NULL,
    tipo_relacion VARCHAR(100) NOT NULL,
    descripcion TEXT,
    CONSTRAINT uk_objeto_veterano_tipo UNIQUE (objeto_museo_id, veterano_id, tipo_relacion),
    CONSTRAINT fk_objeto_veterano_objeto FOREIGN KEY (objeto_museo_id) REFERENCES objetos_museo (id),
    CONSTRAINT fk_objeto_veterano_veterano FOREIGN KEY (veterano_id) REFERENCES veteranos (id)
);

CREATE TABLE ubicaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_eliminacion TIMESTAMP,
    nombre VARCHAR(120) NOT NULL,
    tipo VARCHAR(80),
    descripcion TEXT,
    CONSTRAINT uk_ubicaciones_nombre UNIQUE (nombre)
);

CREATE TABLE inventarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_eliminacion TIMESTAMP,
    objeto_museo_id BIGINT NOT NULL,
    ubicacion_id BIGINT NOT NULL,
    estado VARCHAR(40) NOT NULL,
    estado_conservacion VARCHAR(40) NOT NULL,
    fecha_ingreso DATE NOT NULL,
    fecha_salida DATE,
    fecha_ultimo_movimiento TIMESTAMP NOT NULL,
    observaciones TEXT,
    CONSTRAINT uk_inventarios_objeto_museo UNIQUE (objeto_museo_id),
    CONSTRAINT fk_inventarios_objeto FOREIGN KEY (objeto_museo_id) REFERENCES objetos_museo (id),
    CONSTRAINT fk_inventarios_ubicacion FOREIGN KEY (ubicacion_id) REFERENCES ubicaciones (id)
);

CREATE TABLE movimientos_inventario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_eliminacion TIMESTAMP,
    objeto_museo_id BIGINT NOT NULL,
    tipo VARCHAR(40) NOT NULL,
    fecha TIMESTAMP NOT NULL,
    ubicacion_origen_id BIGINT,
    ubicacion_destino_id BIGINT,
    usuario_id BIGINT,
    observaciones TEXT,
    CONSTRAINT fk_movimientos_inventario_objeto FOREIGN KEY (objeto_museo_id) REFERENCES objetos_museo (id),
    CONSTRAINT fk_movimientos_inventario_ubicacion_origen FOREIGN KEY (ubicacion_origen_id) REFERENCES ubicaciones (id),
    CONSTRAINT fk_movimientos_inventario_ubicacion_destino FOREIGN KEY (ubicacion_destino_id) REFERENCES ubicaciones (id),
    CONSTRAINT fk_movimientos_inventario_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
);

CREATE TABLE exhibiciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_eliminacion TIMESTAMP,
    nombre VARCHAR(160) NOT NULL,
    descripcion TEXT,
    tipo VARCHAR(30) NOT NULL,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE,
    estado VARCHAR(30) NOT NULL
);

CREATE TABLE exhibicion_objeto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_eliminacion TIMESTAMP,
    exhibicion_id BIGINT NOT NULL,
    objeto_museo_id BIGINT NOT NULL,
    fecha_inclusion DATE NOT NULL,
    fecha_retiro DATE,
    estado VARCHAR(40) NOT NULL,
    devolucion_verificada BOOLEAN NOT NULL DEFAULT FALSE,
    verificado_por_usuario_id BIGINT,
    fecha_verificacion TIMESTAMP,
    observaciones_devolucion TEXT,
    CONSTRAINT uk_exhibicion_objeto UNIQUE (exhibicion_id, objeto_museo_id),
    CONSTRAINT fk_exhibicion_objeto_exhibicion FOREIGN KEY (exhibicion_id) REFERENCES exhibiciones (id),
    CONSTRAINT fk_exhibicion_objeto_objeto FOREIGN KEY (objeto_museo_id) REFERENCES objetos_museo (id),
    CONSTRAINT fk_exhibicion_objeto_usuario FOREIGN KEY (verificado_por_usuario_id) REFERENCES usuarios (id)
);

CREATE TABLE relaciones_objetos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_eliminacion TIMESTAMP,
    objeto_origen_id BIGINT NOT NULL,
    objeto_destino_id BIGINT NOT NULL,
    tipo_relacion VARCHAR(80) NOT NULL,
    descripcion TEXT,
    CONSTRAINT uk_relacion_objeto_direccional UNIQUE (objeto_origen_id, objeto_destino_id, tipo_relacion),
    CONSTRAINT fk_relaciones_objetos_origen FOREIGN KEY (objeto_origen_id) REFERENCES objetos_museo (id),
    CONSTRAINT fk_relaciones_objetos_destino FOREIGN KEY (objeto_destino_id) REFERENCES objetos_museo (id)
);

CREATE TABLE auditorias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_eliminacion TIMESTAMP,
    usuario_id BIGINT,
    fecha TIMESTAMP NOT NULL,
    tipo_operacion VARCHAR(30) NOT NULL,
    entidad VARCHAR(120) NOT NULL,
    entidad_id BIGINT NOT NULL,
    datos_previos TEXT,
    datos_nuevos TEXT,
    CONSTRAINT fk_auditorias_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
);

CREATE INDEX idx_objeto_museo_numero_inventario ON objetos_museo (numero_inventario);
CREATE INDEX idx_objeto_museo_nombre ON objetos_museo (nombre);
CREATE INDEX idx_objeto_categoria_objeto ON objeto_categoria (objeto_museo_id);
CREATE INDEX idx_objeto_categoria_categoria ON objeto_categoria (categoria_objeto_id);
CREATE INDEX idx_objeto_depositante_objeto ON objeto_depositante (objeto_museo_id);
CREATE INDEX idx_objeto_depositante_depositante ON objeto_depositante (depositante_id);
CREATE INDEX idx_actuacion_veterano ON actuaciones_veteranos (veterano_id);
CREATE INDEX idx_objeto_veterano_objeto ON objeto_veterano (objeto_museo_id);
CREATE INDEX idx_objeto_veterano_veterano ON objeto_veterano (veterano_id);
CREATE INDEX idx_inventario_objeto ON inventarios (objeto_museo_id);
CREATE INDEX idx_inventario_ubicacion ON inventarios (ubicacion_id);
CREATE INDEX idx_movimiento_inventario_objeto_fecha ON movimientos_inventario (objeto_museo_id, fecha);
CREATE INDEX idx_movimiento_inventario_ubicacion_origen ON movimientos_inventario (ubicacion_origen_id);
CREATE INDEX idx_movimiento_inventario_ubicacion_destino ON movimientos_inventario (ubicacion_destino_id);
CREATE INDEX idx_movimiento_inventario_usuario ON movimientos_inventario (usuario_id);
CREATE INDEX idx_exhibicion_estado ON exhibiciones (estado);
CREATE INDEX idx_exhibicion_objeto_exhibicion ON exhibicion_objeto (exhibicion_id);
CREATE INDEX idx_exhibicion_objeto_objeto_estado ON exhibicion_objeto (objeto_museo_id, estado);
CREATE INDEX idx_relacion_objeto_origen ON relaciones_objetos (objeto_origen_id);
CREATE INDEX idx_relacion_objeto_destino ON relaciones_objetos (objeto_destino_id);
CREATE INDEX idx_relacion_objeto_origen_destino ON relaciones_objetos (objeto_origen_id, objeto_destino_id);
CREATE INDEX idx_auditoria_entidad ON auditorias (entidad, entidad_id);
CREATE INDEX idx_auditoria_fecha ON auditorias (fecha);
CREATE INDEX idx_auditoria_usuario ON auditorias (usuario_id);
