CREATE TABLE detalles_estado_conservacion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_eliminacion TIMESTAMP,
    codigo VARCHAR(80) NOT NULL,
    nombre VARCHAR(160) NOT NULL,
    descripcion TEXT,
    CONSTRAINT uk_detalle_conservacion_codigo UNIQUE (codigo)
);

CREATE INDEX idx_detalle_conservacion_nombre ON detalles_estado_conservacion (nombre);
CREATE INDEX idx_detalle_conservacion_activo ON detalles_estado_conservacion (activo);

INSERT INTO detalles_estado_conservacion (codigo, nombre) VALUES
    ('ABOLSADOS', 'Abolsados'),
    ('ADHESION_DE_HOJAS', 'Adhesion de hojas'),
    ('ANIMALES_MENORES', 'Animales menores'),
    ('CRAQUELADOS', 'Craquelados'),
    ('DECOLORACION', 'Decoloracion'),
    ('DEFORMACIONES', 'Deformaciones'),
    ('DESCOSIDO', 'Descosido'),
    ('DESENCUADERNADO', 'Desencuadernado'),
    ('DESFASES', 'Desfases'),
    ('DESGASTE', 'Desgaste'),
    ('DESPRENDIMIENTOS', 'Desprendimientos'),
    ('DESTENSADOS', 'Destensados'),
    ('DOBLECES', 'Dobleces'),
    ('EXFOLIACIONES', 'Exfoliaciones'),
    ('FALTA_DE_ADHESION', 'Falta de adhesion'),
    ('FALTANTE', 'Faltante'),
    ('FALTANTE_DE_CUERPO', 'Faltante de cuerpo'),
    ('FALTANTE_DE_LOMO', 'Faltante de lomo'),
    ('FALTANTE_DE_SOPORTE', 'Faltante de soporte'),
    ('FALTANTE_DE_TAPA', 'Faltante de tapa'),
    ('FRACTURAS', 'Fracturas'),
    ('GOLPES', 'Golpes'),
    ('GRIETAS', 'Grietas'),
    ('HONGOS', 'Hongos'),
    ('HUELLAS_DE_HUMEDAD', 'Huellas de humedad'),
    ('HUNDIMIENTOS', 'Hundimientos'),
    ('INSECTOS', 'Insectos'),
    ('LAGUNAS', 'Lagunas'),
    ('MANCHAS', 'Manchas'),
    ('MARCAS', 'Marcas'),
    ('MICROORGANISMOS', 'Microorganismos'),
    ('OXIDACION', 'Oxidacion'),
    ('OXIDACION_DE_TINTA', 'Oxidacion de tinta'),
    ('PERDIDA_DE_TINTA', 'Perdida de tinta'),
    ('POLVO', 'Polvo'),
    ('QUEMADURAS', 'Quemaduras'),
    ('RASGADURAS', 'Rasgaduras'),
    ('RAYADURAS', 'Rayaduras'),
    ('ROTURA', 'Rotura'),
    ('SALES', 'Sales'),
    ('SOBREPINTURA', 'Sobrepintura'),
    ('SUCIEDAD_SUPERFICIAL', 'Suciedad superficial'),
    ('SUCIO', 'Sucio');

ALTER TABLE objeto_museo_detalles_conservacion ADD COLUMN detalle_id BIGINT;

UPDATE objeto_museo_detalles_conservacion odc
SET detalle_id = dec.id
FROM detalles_estado_conservacion dec
WHERE dec.codigo = odc.detalle;

ALTER TABLE objeto_museo_detalles_conservacion ALTER COLUMN detalle_id SET NOT NULL;
ALTER TABLE objeto_museo_detalles_conservacion DROP CONSTRAINT pk_objeto_museo_detalles_conservacion;
ALTER TABLE objeto_museo_detalles_conservacion DROP COLUMN detalle;
ALTER TABLE objeto_museo_detalles_conservacion ADD CONSTRAINT pk_objeto_museo_detalles_conservacion PRIMARY KEY (objeto_museo_id, detalle_id);
ALTER TABLE objeto_museo_detalles_conservacion
    ADD CONSTRAINT fk_objeto_museo_detalles_conservacion_detalle
    FOREIGN KEY (detalle_id) REFERENCES detalles_estado_conservacion(id);
