ALTER TABLE objetos_museo
    ADD COLUMN denominacion_objeto VARCHAR(160),
    ADD COLUMN descripcion_tecnica TEXT,
    ADD COLUMN materiales TEXT,
    ADD COLUMN dimensiones TEXT,
    ADD COLUMN estado_conservacion VARCHAR(40);

UPDATE objetos_museo
SET denominacion_objeto = nombre
WHERE denominacion_objeto IS NULL;

ALTER TABLE objetos_museo
    ALTER COLUMN denominacion_objeto SET NOT NULL;

CREATE INDEX idx_objeto_museo_denominacion ON objetos_museo (denominacion_objeto);

CREATE TABLE fotos_objeto_museo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_eliminacion TIMESTAMP,
    objeto_museo_id BIGINT NOT NULL,
    nombre_archivo VARCHAR(255) NOT NULL,
    content_type VARCHAR(120) NOT NULL,
    tamanio_bytes BIGINT NOT NULL,
    ruta_almacenamiento VARCHAR(500) NOT NULL,
    descripcion TEXT,
    fecha_carga TIMESTAMP NOT NULL,
    cargado_por VARCHAR(160),
    CONSTRAINT fk_fotos_objeto_museo_objeto
        FOREIGN KEY (objeto_museo_id) REFERENCES objetos_museo(id)
);

CREATE INDEX idx_fotos_objeto_museo_objeto ON fotos_objeto_museo (objeto_museo_id);

CREATE TABLE recibos_ingreso_objeto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_eliminacion TIMESTAMP,
    numero_recibo VARCHAR(80) NOT NULL,
    fecha_emision TIMESTAMP NOT NULL,
    objeto_museo_id BIGINT NOT NULL,
    depositante_id BIGINT NOT NULL,
    numero_inventario VARCHAR(80) NOT NULL,
    denominacion_objeto VARCHAR(160) NOT NULL,
    descripcion_breve TEXT NOT NULL,
    depositante_nombre VARCHAR(160) NOT NULL,
    depositante_contacto VARCHAR(160),
    operador VARCHAR(160),
    texto_constancia TEXT NOT NULL,
    copia_firmada_nombre_archivo VARCHAR(255),
    copia_firmada_content_type VARCHAR(120),
    copia_firmada_tamanio_bytes BIGINT,
    copia_firmada_ruta_almacenamiento VARCHAR(500),
    copia_firmada_fecha_carga TIMESTAMP,
    copia_firmada_cargado_por VARCHAR(160),
    CONSTRAINT uk_recibos_ingreso_numero UNIQUE (numero_recibo),
    CONSTRAINT fk_recibo_objeto
        FOREIGN KEY (objeto_museo_id) REFERENCES objetos_museo(id),
    CONSTRAINT fk_recibo_depositante
        FOREIGN KEY (depositante_id) REFERENCES depositantes(id)
);

CREATE INDEX idx_recibos_ingreso_objeto ON recibos_ingreso_objeto (objeto_museo_id);
CREATE INDEX idx_recibos_ingreso_depositante ON recibos_ingreso_objeto (depositante_id);
