ALTER TABLE fotos_objeto_museo
    ADD COLUMN nombre_archivo_original VARCHAR(255),
    ADD COLUMN nombre_archivo_almacenado VARCHAR(255),
    ADD COLUMN ruta_relativa VARCHAR(500);

UPDATE fotos_objeto_museo
SET nombre_archivo_original = nombre_archivo,
    nombre_archivo_almacenado = regexp_replace(nombre_archivo, '[^A-Za-z0-9._-]', '_', 'g')
WHERE nombre_archivo_original IS NULL;

CREATE TABLE recibos_escaneados_objeto_museo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_eliminacion TIMESTAMP,
    objeto_museo_id BIGINT NOT NULL,
    nombre_archivo_original VARCHAR(255) NOT NULL,
    nombre_archivo_almacenado VARCHAR(255) NOT NULL,
    content_type VARCHAR(120) NOT NULL,
    tamanio_bytes BIGINT NOT NULL,
    ruta_relativa VARCHAR(500) NOT NULL,
    fecha_carga TIMESTAMP NOT NULL,
    cargado_por VARCHAR(160),
    CONSTRAINT fk_recibos_escaneados_objeto
        FOREIGN KEY (objeto_museo_id) REFERENCES objetos_museo(id)
);

CREATE INDEX idx_recibos_escaneados_objeto ON recibos_escaneados_objeto_museo (objeto_museo_id);
CREATE UNIQUE INDEX uk_recibo_escaneado_activo_objeto
    ON recibos_escaneados_objeto_museo (objeto_museo_id)
    WHERE eliminado = FALSE;
