export {
  buscarActuacionesVeteranos,
  buscarVeteranos,
  buscarUnidadesMilitares,
  listarRangosMilitares,
  actualizarActuacionVeterano,
  actualizarVeterano,
  asociarObjetoAVeterano,
  bajaLogicaActuacionVeterano,
  bajaLogicaVeterano,
  crearActuacionVeterano,
  crearVeterano,
  subirImagenesVeterano,
  listarVideosVeterano,
  listarImagenesVeterano,
  eliminarVideoVeterano,
  eliminarImagenVeterano,
  descargarImagenVeterano,
  crearVideoVeterano,
  actualizarVideoVeterano,
  eliminarRelacionObjetoVeterano,
  listarActuacionesPorVeterano,
  listarActuacionesVeteranos,
  listarObjetosRelacionadosAVeterano,
  listarRelacionesObjetoVeterano,
  listarVeteranos,
  obtenerActuacionVeteranoPorId,
  obtenerRelacionObjetoVeteranoPorId,
  obtenerVeteranoPorId
} from "./veteranos-api";

export type { BuscarActuacionesVeteranosParams, BuscarVeteranosParams } from "./veteranos-api";
