export {
  buscarUnidadesMilitares,
  listarRangosMilitares,
  actualizarActuacionVeterano,
  actualizarVeterano,
  asociarObjetoAVeterano,
  bajaLogicaActuacionVeterano,
  bajaLogicaVeterano,
  crearActuacionVeterano,
  crearVeterano,
  eliminarRelacionObjetoVeterano,
  listarActuacionesPorVeterano,
  listarActuacionesVeteranos,
  listarObjetosRelacionadosAVeterano,
  listarRelacionesObjetoVeterano,
  listarVeteranos,
  obtenerActuacionVeteranoPorId,
  obtenerRelacionObjetoVeteranoPorId,
  obtenerVeteranoPorId
} from "./veteranos-api";
