export {
  actualizarObjeto,
  bajaLogicaObjeto,
  buscarObjetos,
  cargaRapidaObjeto,
  crearObjeto,
  descargarCopiaFirmadaRecibo,
  descargarFotoObjeto,
  descargarReciboEscaneadoObjeto,
  descargarReciboPdf,
  eliminarFotoObjeto,
  eliminarReciboEscaneadoObjeto,
  listarFotosObjeto,
  listarMovimientosObjeto,
  listarObjetos,
  listarObjetosEliminados,
  listarObjetosPendientesCompletar,
  listarRecibosObjeto,
  moverObjeto,
  obtenerObjetoPorId,
  obtenerReciboEscaneadoObjeto,
  restaurarObjeto,
  subirCopiaFirmadaRecibo,
  subirFotoObjeto,
  subirFotosObjeto,
  subirReciboEscaneadoObjeto
} from "./objetos-api";
