export {
  actualizarObjeto,
  bajaLogicaObjeto,
  buscarObjetos,
  cargaRapidaObjeto,
  crearObjeto,
  descargarCopiaFirmadaRecibo,
  descargarFotoObjeto,
  descargarReciboPdf,
  eliminarFotoObjeto,
  listarFotosObjeto,
  listarObjetos,
  listarObjetosEliminados,
  listarObjetosPendientesCompletar,
  listarRecibosObjeto,
  obtenerObjetoPorId,
  restaurarObjeto,
  subirCopiaFirmadaRecibo,
  subirFotoObjeto
} from "./objetos-api";
